### ISSUE TITLE
Feature request: wisp to inform players

### ISSUE THREAD

**Issue by cipriant** [uakfdotb/gcb#23]
will be great if gcb can inform (via a whisper, not a chat window) a banned player when try to join in lobby like this: [GCB] you are banned: reason : MH#.
And the second part is to inform players who try to join in lobby but  is full: wisper "no more free slots". i req. this becouse some players think are banned when gamelist show 10/11 and they cannot join.

**Comment by uakfdotb** [comment]
This requires a greater level of interaction between gcb and GHost++, I prefer to keep them separate. You could try modifying GarenaTCP to capture that information and perform the relevant chat actions via the GarenaInterface API.

**Comment by cipriant** [comment]
"You could try modifying GarenaTCP to capture that information and perform the relevant chat actions via the GarenaInterface API."
i dont know how to do that, mby you can done this and activate config.
regards
