### ISSUE TITLE
The main problem GCB

### ISSUE THREAD

**Issue by TemKaSD** [uakfdotb/gcb#26]
Hi, I'm more than a year using GCB, it does have one very big disadvantage, please help to understand.

I specifically scored his Internet channel to test.
When I play straight through Battle.net, all is well, lags have but there is no connection breaks.
When playing through Garena (GCB) immediately eject from the game after waiting administrator.

Because of what is going on? How to fix it or reduce the breaks?

Here is the error: [GarenaTCP -478944396] Terminating connection -478944396 with /IP  (Name)

**Comment by Artyom91** [comment]
@uakfdotb Fixed: https://www.ghostpp.com/forum/index.php?topic=458 comment please.
