### ISSUE TITLE
Как запустить GCB b BNET на одном порту?

### ISSUE THREAD

**Issue by Artyom91** [uakfdotb/gcb#27]
Здравствуйте, я поставил Bnet и gcb, но они должны слушать один порт, как мне запустить GCB с привязкой к IP адресу?

GCB сейчас выглядит так:
![2014-12-31_134909](https://cloud.githubusercontent.com/assets/6318282/5585334/d9bb1c8e-90f3-11e4-9985-9db5f46f2261.png)

BNET нормально привязывается:

![2014-12-31_135102](https://cloud.githubusercontent.com/assets/6318282/5585349/1bc4222e-90f4-11e4-94f1-fee01acfef6d.png)

**Comment by Artyom91** [comment]
@uakfdotb Hi, how to run the GCB at a certain IP address? See screenshot 1.

**Comment by Artyom91** [comment]
he Set.

**Comment by Artyom91** [comment]
@uakfdotb help?

**Comment by HarpyWar** [comment]
You set the same IP and port `149.154.66.23` both for gcb and pvpgn.
Only one program can listen a single port on a single IP at the same time.
