### ISSUE TITLE
How to run GCB on a specific IP address?

### ISSUE THREAD

**Issue by Artyom91** [uakfdotb/gcb#28]
@uakfdotb 

I set in the config parameters:

![2015-01-31_073103](https://cloud.githubusercontent.com/assets/6318282/5983674/280a3ade-a91b-11e4-9964-2f818c9538e7.png)

IP address is not assigned:

![2015-01-31_070556](https://cloud.githubusercontent.com/assets/6318282/5983289/b274dba6-a917-11e4-9dbf-a559359caf24.png)

How to fix it?

**Comment by uakfdotb** [comment]
The bind address is used when connecting to external servers such as the room and the Garena authentication server. If you want the WC3Interface to also listen on that IP address, you'll have to edit WC3Interface.java (look for "new DatagramSocket").

**Comment by Artyom91** [comment]
@uakfdotb 

socket = new DatagramSocket(broadcast_port);

Replace

bindaddress = GCBConfig.configuration.getInt("gcb_bindaddress", BIND_ADDRESS);
socket = new DatagramSocket(bindaddress:broadcast_port);

Right?

**Comment by uakfdotb** [comment]
Uh, it should be

```
String bindaddress = GCBConfig.configuration.getString("gcb_bindaddress", "0.0.0.0");
socket = new DatagramSocket(broadcast_port, InetAddress.getByName(bindaddress));
```

**Comment by Artyom91** [comment]
@uakfdotb How to Compile?

I created a file manifest.txt in src/gcb

Manifest-Version: 2.0
Class-Path: . lib/bcpkix-jdk15on-148.jar lib/bcprov-jdk15on-148.jar lib/commons-collections-3.2.1.jar lib/commons-configuration-1.9.jar lib/commons-lang-2.6.jar lib/commons-logging-1.1.2.jar lib/mysql-connector-java-5.1.24-bin.jar
Main-Class: Main.class

no main manifest attribute, in gcb.jar

**Comment by Artyom91** [comment]
Help please https://www.ghostpp.com/forum/index.php?topic=414.msg2625#new

**Comment by Artyom91** [comment]
@uakfdotb Help please https://www.ghostpp.com/forum/index.php?topic=414.msg2875#msg2875

**Comment by TemKaSD** [comment]
@uakfdotb After making changes does not see the game in Garena. It only works with the address 0.0.0.0
Help please.
