### ISSUE TITLE
fix rank Vip in GCB

### ISSUE THREAD

**Issue by aDvinking** [uakfdotb/gcb#29]
hi
fix rank Vip in GCB

See [03:48:14] [System Message] V.I.P < username> has entered the room

plz fix it

&
all commands to Whisper  display Except Command : Staff 

TanQ

**Comment by uakfdotb** [comment]
Hi, unfortunately the room bot portion of gcb is no longer supported. Consider using https://code.google.com/p/garena-room-control/ instead

**Comment by aDvinking** [comment]
link Can not open

**Comment by aDvinking** [comment]
Can you update the bot problems be solved?
