### ISSUE TITLE
Help compiled GCB

### ISSUE THREAD

**Issue by Artyom91** [uakfdotb/gcb#31]
Help compiled GCB.

I run command:
javac -classpath .:../bin/lib/* gcb/Main.java
java -classpath .:../bin/lib/* gcb.Main

All is well, GCB works. How now do it in gcb.jar?

**Comment by Artyom91** [comment]
@uakfdotb Help please..

**Comment by uakfdotb** [comment]
Try this -- http://www.skylit.com/javamethods/faqs/createjar.html

The issue tracker is more for reporting bugs and requesting features, not for support. Please use https://ghostpp.com/ for help.

**Comment by Artyom91** [comment]
@uakfdotb Help please https://www.ghostpp.com/forum/index.php?topic=414.msg3014#msg3014
