### ISSUE TITLE
Will gcb work if I change gcb_broadcastport?

### ISSUE THREAD

**Issue by SimpleCold** [uakfdotb/gcb#33]
Java binds 6112 port by default settings, which makes warcraft III unusable, cause it too wants to bind this port.
{Everyone else joins my ghost++ game on PC just fine, and play without me ;( }.
Question is, if I change it to another number, will Garena clients still be able to connect to my Ghost++ instance?

**Comment by uakfdotb** [comment]
Yes, but you need to modify your host bot to broadcast packets to the new port, GHost++ by default only broadcasts to UDP port 6112.

```
m_GHost->m_UDPSocket->Broadcast( 6112 ....
```

**Comment by SimpleCold** [comment]
Huge thanks, I knew you were a nice guy!
Such an easy fix, thanks for info!
