### ISSUE TITLE
How rebordcast game from warcraft III?

### ISSUE THREAD

**Issue by kirill-782** [uakfdotb/gcb#35]
How rebordcast game from warcraft III? how to setup config GCB that start rebordcast Warcraft III game at garena. I do not want to use Ghost

> In short, I want to make it through GCB so that the game can be seen in 2+ rooms without the Ghost

**Comment by uakfdotb** [comment]
It should be the same as setting it up for GHost++.

**Comment by kirill-782** [comment]
And you can without Ghost? Only GCB and WC3?

**Comment by uakfdotb** [comment]
Yes theoretically it should work, one problem is that gcb will need to listen on UDP 6112 but WC3 might take over that port.

**Comment by kirill-782** [comment]
I have 2 computers. But I do not know how to tune in to another address and do not know which port to put

**Comment by Gymi9** [comment]
Hello guys. GCB often spam about creating games, how to remove spam chat Garena?  I use bot Ghost one 1.17

**Comment by vmarkaljon** [comment]
what is the new mainhost for GCB?
