### ISSUE TITLE
GCB autobanned

### ISSUE THREAD

**Issue by hagiali** [uakfdotb/gcb#37]
Hi guys,
After 2 years I tried to host to russia TD rooms and every time I'm auto banned with reason "bot-detected". 
It looks like gcb has a signature and the russians stuf kick and ban all the bots who don't pay for hosting, Garena Singapore don't care about that, they abandoned the support for w3.
Question. How they detect the gcb signature? if i join with garena client i'm not banned.

**Comment by Profforgr** [comment]
How is your bot named? Which maps do you host? What's your aim?

**Comment by styla01** [comment]
@hagiali 
lolz, how much money did he ask you? In my case they ask for more because I m not from russia. Here is a print: https://imgur.com/a/lNKdD#5oCapvN
Profforgr wont help you, he work with/for them

I don't pay. Maybe uakf can make a patch to avoid detection or tell us what can we do... And right, if I join with garena lan client I'm not banned, they only gcb detect and ban ...

**Comment by kirill-782** [comment]
@styla01
1) GameName = garena login
2) (WC3 UDP) HostName = Garena login
3) gcb_broadcastfilter_cache = true
4) gcb_broadcastfilter_key = true
(Not sure) 1 room 1 garena account

If you do let me know.

**Comment by styla01** [comment]
I dont understood you, Can u make a print with config please?

**Comment by kirill-782** [comment]
I thought that the bot defines the host of bots by udp packets suggesting to fit them under wc3. After I noticed that the bot determines the GCB itself. Rummaging through the traffic, I found 2 bytes that were issued by GCB. I corrected them and I was able to play games for 2 days in Garena. After the bot, they took me and again kicked me.

**Comment by styla01** [comment]
@kirill-782 I understood now.  Do you have discord or skype?

@uakfdotb  Can you help us with some hints? You can test gcb in any russian rooms to see the issue.

**Comment by kirill-782** [comment]
@styla01
I do not speak English

**Comment by styla01** [comment]
we can speak with google translate

**Comment by kirill-782** [comment]
@styla01 okay
skype kirill.7827

**Comment by vmarkaljon** [comment]
what mainhost are you using now? con3.garenaconnect.com not working anymore. please
