### ISSUE TITLE
Unable to locate main host: con3.garenaconnect.com

### ISSUE THREAD

**Issue by TemKaSD** [uakfdotb/gcb#41]
[GInterface 50] Unable to locate main host: con3.garenaconnect.com
[GarenaReconnect] GARENA_MAIN disconnected; reconnecting shortly...

@uakfdotb con3.garenaconnect.com - not work. How to fix?

**Comment by vmarkaljon** [comment]
@uakfdotb con3.garenaconnect.com - not work. How to fix?
please I wanna know what is new mainhost and working

**Comment by vmarkaljon** [comment]
please reply
