### ISSUE TITLE
what is the problem 

### ISSUE THREAD

**Issue by vmarkaljon** [uakfdotb/gcb#43]
D:\My Files\My Games\GCB\gcb-gcb1.0.1\bin>java -jar gcb.jar
gcb 1.0.1
[GInterface 1] Initializing...
[GEncrypt] Initializing AES Keys...
[GEncrypt] Initializing RSA Keys...
[GEncrypt] Reading private key in PEM format...
[GInterface 1] Connecting to 119.28.110.234...
[GInterface 1] Using local port: 54071
[GInterface 1] Initializing peer socket...
[GInterface 1] Autoset peerport=62216
[GInterface 1] Sending GSP session init...
[GInterface 1] Reading GSP session init reply...
[GInterface 1] GSP session init reply received!
[GInterface 1] Sending GSP session hello...
[GInterface 1] Reading GSP session hello reply...
[GInterface 1] GSP session hello reply received!
[GInterface 1] Sending GSP session login...
[GEncrypt] Internal IP address determined at 192.168.254.173
[GInterface 1] Reading GSP session login reply...
[GInterface 1] Successfully logged in!
[GInterface 1] Server says your ID is: 436382918
[GInterface 1] Server says your username is: BOT-ENT.HOSTING
[GInterface 1] Server says your country is: PH
[GInterface 1] Server says your experience is: 1
[GInterface 1] Server says your email address is:
[Main] Waiting for lookup response on connection 1...
[GInterface 1] PeerLoop: set address to 110.54.240.18 and port to 12797
[Main] Received lookup response!
[GInterface 1] Connecting to room...
[GInterface 1] Conducting hostname lookup...
[GInterface 1] Connecting to 203.117.124.13...
[STATUS] connected: 0 (max: 0/0); mem: 15872 KB; threads: 17; rooms/users: 1/0; up: 10s
[GInterface 1] Error while connecting to room host: Connection timed out: connect
[GarenaReconnect] GARENA_ROOM disconnected; reconnecting shortly...

**Comment by vmarkaljon** [comment]
please help i beg. I can't use GCB after all 7 servers are gone

**Comment by uakfdotb** [comment]
Sorry, I am not working on this anymore and I do not have Garena installed.

One thought is, perhaps you need to update the rooms database using this: https://github.com/uakfdotb/gcb/tree/master/gcb_list . Have you already tried updating the rooms database like that?

**Comment by vmarkaljon** [comment]
uakfdotb thank you for fast reply.
Im using old update of rooms database because I can't find the newer.

**Comment by uakfdotb** [comment]
Is there any file "roomen.dat" in your Garena installation?

If not, maybe you need to do Wireshark when you are using Garena to see where it is connecting when you join a Garena room, and then take the IP and stick it in your gcb configuration file for the room IP.

**Comment by vmarkaljon** [comment]
Thank you for Another option Sir. uakfdotb maybe this one will work. Thank you for still helping

**Comment by vmarkaljon** [comment]
Sir thank you so much! 
I can connect now
I find the solution thank you thank you for your help
Now I can broadcast garena again
